-- ==========================================
-- SafeNest Supabase Database Setup
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Users Table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT CHECK (role IN ('child', 'parent')) DEFAULT 'child',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  description TEXT NOT NULL,
  report_type TEXT DEFAULT 'unsafe_situation',
  ai_risk_level TEXT,
  status TEXT DEFAULT 'pending',
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SOS Alerts Table
CREATE TABLE IF NOT EXISTS public.sos_alerts (
  alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  latitude DOUBLE PRECISION NOT NULL DEFAULT 0,
  longitude DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Add report_type column if running on existing schema
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS report_type TEXT DEFAULT 'unsafe_situation';

-- 5. Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sos_alerts ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Users can view own profile" ON public.users;
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.users;
DROP POLICY IF EXISTS "Users can view own reports" ON public.reports;
DROP POLICY IF EXISTS "Users can insert own reports" ON public.reports;
DROP POLICY IF EXISTS "Users can insert own alerts" ON public.sos_alerts;
DROP POLICY IF EXISTS "Users can view own alerts" ON public.sos_alerts;

-- Users
CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.users
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Reports
CREATE POLICY "Users can view own reports" ON public.reports
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own reports" ON public.reports
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- SOS Alerts
CREATE POLICY "Users can insert own alerts" ON public.sos_alerts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own alerts" ON public.sos_alerts
  FOR SELECT USING (auth.uid() = user_id);

-- 7. Auto-create user profile on sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, role)
  VALUES (NEW.id, NEW.email, 'child')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. Family Links Table
CREATE TABLE IF NOT EXISTS public.family_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id UUID REFERENCES auth.users(id) NOT NULL,
  child_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(parent_id, child_id)
);

ALTER TABLE public.family_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Parents can manage their links" ON public.family_links;
DROP POLICY IF EXISTS "Children can read their links" ON public.family_links;

CREATE POLICY "Parents can manage their links" ON public.family_links
  FOR ALL USING (auth.uid() = parent_id);

CREATE POLICY "Children can read their links" ON public.family_links
  FOR SELECT USING (auth.uid() = child_id);

-- 9. Safe Zones Table
CREATE TABLE IF NOT EXISTS public.safe_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id UUID REFERENCES auth.users(id) NOT NULL,
  child_id UUID REFERENCES auth.users(id),
  name TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  radius_meters INT NOT NULL DEFAULT 100,
  required_from TIME,
  required_until TIME,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.safe_zones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Parents manage zones" ON public.safe_zones;
DROP POLICY IF EXISTS "Children read their zones" ON public.safe_zones;

CREATE POLICY "Parents manage zones" ON public.safe_zones
  FOR ALL USING (auth.uid() = parent_id);

CREATE POLICY "Children read their zones" ON public.safe_zones
  FOR SELECT USING (auth.uid() = child_id);

-- 10. Zone Events Table (entered/exited/missing) — parent_id for fast per-parent queries
CREATE TABLE IF NOT EXISTS public.zone_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id BIGINT REFERENCES public.safe_zones(id) ON DELETE CASCADE,
  child_id UUID REFERENCES auth.users(id) NOT NULL,
  parent_id UUID REFERENCES auth.users(id),
  event_type TEXT CHECK (event_type IN ('entered', 'exited', 'missing')) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.zone_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Children insert zone events" ON public.zone_events;
DROP POLICY IF EXISTS "Parents read zone events" ON public.zone_events;

CREATE POLICY "Children insert zone events" ON public.zone_events
  FOR INSERT WITH CHECK (auth.uid() = child_id);

CREATE POLICY "Parents read zone events" ON public.zone_events
  FOR SELECT USING (auth.uid() = parent_id);

-- 11. Check-ins Table
CREATE TABLE IF NOT EXISTS public.check_ins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_id UUID REFERENCES auth.users(id) NOT NULL,
  parent_id UUID REFERENCES auth.users(id),
  note TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.check_ins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Children insert check-ins" ON public.check_ins;
DROP POLICY IF EXISTS "Parents read check-ins" ON public.check_ins;
DROP POLICY IF EXISTS "Children read own check-ins" ON public.check_ins;

CREATE POLICY "Children insert check-ins" ON public.check_ins
  FOR INSERT WITH CHECK (auth.uid() = child_id);

CREATE POLICY "Parents read check-ins" ON public.check_ins
  FOR SELECT USING (auth.uid() = parent_id);

CREATE POLICY "Children read own check-ins" ON public.check_ins
  FOR SELECT USING (auth.uid() = child_id);

-- 12. Location Shares Table (replaces misuse of sos_alerts for manual location sharing)
CREATE TABLE IF NOT EXISTS public.location_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_id UUID REFERENCES auth.users(id) NOT NULL,
  parent_id UUID REFERENCES auth.users(id) NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.location_shares ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Children insert location shares" ON public.location_shares;
DROP POLICY IF EXISTS "Parents read location shares" ON public.location_shares;
DROP POLICY IF EXISTS "Children read own location shares" ON public.location_shares;

CREATE POLICY "Children insert location shares" ON public.location_shares
  FOR INSERT WITH CHECK (auth.uid() = child_id);

CREATE POLICY "Parents read location shares" ON public.location_shares
  FOR SELECT USING (auth.uid() = parent_id);

CREATE POLICY "Children read own location shares" ON public.location_shares
  FOR SELECT USING (auth.uid() = child_id);

-- 13. Live Locations Table (child pushes every 30s; one row per child via upsert)
CREATE TABLE IF NOT EXISTS public.live_locations (
  child_id UUID REFERENCES auth.users(id) NOT NULL PRIMARY KEY,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.live_locations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Children upsert own live location" ON public.live_locations;
DROP POLICY IF EXISTS "Parents read live locations of linked children" ON public.live_locations;

CREATE POLICY "Children upsert own live location" ON public.live_locations
  FOR ALL USING (auth.uid() = child_id)
  WITH CHECK (auth.uid() = child_id);

-- Parents can read live locations of children linked to them
CREATE POLICY "Parents read live locations of linked children" ON public.live_locations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.family_links
      WHERE family_links.parent_id = auth.uid()
        AND family_links.child_id = live_locations.child_id
    )
  );

-- 14. Emergency Contacts Table (parents manage; children read)
CREATE TABLE IF NOT EXISTS public.emergency_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_id UUID REFERENCES auth.users(id) NOT NULL,
  label TEXT NOT NULL,
  phone TEXT NOT NULL,
  icon_name TEXT DEFAULT 'person',
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Parents manage emergency contacts" ON public.emergency_contacts;
DROP POLICY IF EXISTS "Children read own emergency contacts" ON public.emergency_contacts;

-- Parents can manage contacts for their linked children
CREATE POLICY "Parents manage emergency contacts" ON public.emergency_contacts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.family_links
      WHERE family_links.parent_id = auth.uid()
        AND family_links.child_id = emergency_contacts.child_id
    )
  );

CREATE POLICY "Children read own emergency contacts" ON public.emergency_contacts
  FOR SELECT USING (auth.uid() = child_id);

-- 15. Add parent_id to sos_alerts (needed for per-parent realtime filtering)
ALTER TABLE public.sos_alerts ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES auth.users(id);

-- Allow parents to read SOS alerts sent to them
DROP POLICY IF EXISTS "Parents read own sos alerts" ON public.sos_alerts;
CREATE POLICY "Parents read own sos alerts" ON public.sos_alerts
  FOR SELECT USING (auth.uid() = parent_id);

-- Enable realtime for parent alert subscriptions
ALTER PUBLICATION supabase_realtime ADD TABLE public.zone_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sos_alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.location_shares;
ALTER PUBLICATION supabase_realtime ADD TABLE public.live_locations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.emergency_contacts;
